project:
  type: website

website:
  title: "Rose McDonald"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: portfolio.qmd
        text: Portfolio
      - href: contact.qmd
        text: Contact
  page-footer:
    center: "© 2025 Rose McDonald"
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
